// Mapping common F1 country names to ISO 3166-1 alpha-2 codes
export const COUNTRY_CODE_OVERRIDES: Record<string, string> = {
    uae: 'ae',
    'united arab emirates': 'ae',
    usa: 'us',
    us: 'us',
    uk: 'gb',
    'united kingdom': 'gb',
    british: 'gb',
    'great britain': 'gb',
    england: 'gb',
    english: 'gb',
    korea: 'kr',
    'south korea': 'kr',
    russia: 'ru',
    russian: 'ru',
    'saudi arabia': 'sa',
    saudi: 'sa',
    bahrein: 'bh',
    bahrain: 'bh',
    bahraini: 'bh',
    china: 'cn',
    chinese: 'cn',
    japan: 'jp',
    japanese: 'jp',
    france: 'fr',
    french: 'fr',
    spain: 'es',
    spanish: 'es',
    italy: 'it',
    italian: 'it',
    germany: 'de',
    german: 'de',
    canada: 'ca',
    canadian: 'ca',
    australia: 'au',
    australian: 'au',
    brazil: 'br',
    brazilian: 'br',
    mexico: 'mx',
    mexican: 'mx',
    singapore: 'sg',
    monaco: 'mc',
    monacan: 'mc',
    monegasque: 'mc',
    austria: 'at',
    austrian: 'at',
    belgium: 'be',
    belgian: 'be',
    netherlands: 'nl',
    dutch: 'nl',
    holland: 'nl',
    dutchman: 'nl',
    hungary: 'hu',
    hungarian: 'hu',
    qatar: 'qa',
    qatari: 'qa',
    india: 'in',
    indian: 'in',
    argentina: 'ar',
    argentinian: 'ar',
    argentine: 'ar',
    chile: 'cl',
    chilean: 'cl',
    portugal: 'pt',
    portuguese: 'pt',
    swiss: 'ch',
    switzerland: 'ch',
    swisss: 'ch',
    american: 'us',
    irish: 'ie',
    ireland: 'ie',
    finnish: 'fi',
    finland: 'fi',
    danish: 'dk',
    denmark: 'dk',
    swedish: 'se',
    sweden: 'se',
    polish: 'pl',
    poland: 'pl',
    thai: 'th',
    thailand: 'th',
    norway: 'no',
    norwegian: 'no',
    'czech republic': 'cz',
    czech: 'cz',
    uruguayan: 'uy',
    'new zealander': 'nz',
    turkey: 'tr',
}

export const toFlagCode = (countryName: string | null): string | null => {
    if (!countryName) return null
    const key = countryName.trim().toLowerCase()
    if (COUNTRY_CODE_OVERRIDES[key]) return COUNTRY_CODE_OVERRIDES[key]
    if (key.length === 2) return key
    if (key.length >= 2) return key.slice(0, 2)
    return null
}
